<a href="https://colab.research.google.com/github/Maurimrs/INT_DS_UNIVESP/blob/main/Biblioteca_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importa a biblioteca numpy

In [ ]:
import numpy as np


Gerar dados aleatórios


Gerar um NDArray de 2x3 (duas listas com 3 elementos


In [ ]:
dados=np.random.rand(2,3)

dados

array([[0.90077812, 0.04464063, 0.81482597],
       [0.43999606, 0.40774743, 0.90016055]])

tipo de array




In [ ]:
dados.dtype

dtype('float64')

Tamanho e quantidade de dimensões

In [ ]:
#serve para ver qual o tamanho e dimensão de qualquer array
dados.shape



(2, 3)

In [ ]:
#serve para ver quantas dimensões ele tem
dados.ndim


2

In [ ]:
#criar NDArray usando a função array
#ao criar o array a função array tenta utilizar o melhor tipo de dado

lista=[1,2,3,4,5,6,7,8,9,30.1]

In [ ]:
dados2=np.array(lista)
dados2


array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 30.1])

In [ ]:
lista2=[1,3,45,5,76,7.1],[2,4,5,6,7,8]

In [ ]:
dados3=np.array(lista2)

dados3

array([[ 1. ,  3. , 45. ,  5. , 76. ,  7.1],
       [ 2. ,  4. ,  5. ,  6. ,  7. ,  8. ]])

In [ ]:
#outra maneiras de criar arrays

#dados com valor 0

dadoszero=np.zeros(10)
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
dadoszero2=np.zeros((2,3))
dadoszero2


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#dados com valor 1
dadosum=np.ones(5)

dadosum


array([1., 1., 1., 1., 1.])

In [ ]:
#dados em sequencia

dadosseq=np.arange(10)
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq2=np.arange(0,20,2)
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dadosseq.dtype

dtype('int64')

In [ ]:
#transformar o tipo

dadosseqf=dadosseq.astype(np.float64)

In [ ]:
dadosseqf.dtype

dtype('float64')

In [ ]:
#aritmetica com arrays

dados4=np.array([[1,2,3],[4,5,6]])

In [ ]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
dados5=dados4+dados4

In [ ]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
#indexação

dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq[5]

5

Diferente de uma lista python, um recorte (fatia) de um ndarray sofrera broadcast - é como se fosse uma view de banco de dados

com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [ ]:
dadosseq[3:6]

array([3, 4, 5])

In [ ]:
dadosseq[3:6]=20

In [ ]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [ ]:
fatiadados=dadosseq[2:4]

In [ ]:
fatiadados

array([ 2, 20])

In [ ]:
fatiadados[1]=2000
fatiadados

array([   2, 2000])

In [ ]:
fatiadados

array([   2, 2000])

In [ ]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [ ]:
#copiar dados

fatia2=dadosseq[2:4].copy()
fatia2

array([   2, 2000])

In [ ]:
fatia2[:]=111
fatia2


array([111, 111])

In [ ]:
#array com mais de uma dimensão

dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])
#sempre a linha ou coluna se inicia em 0
dados6


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dados6[1,2]

6

In [ ]:
#mascaras

dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [ ]:
mascara=(dadosseq<100)
mascara

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
#vai atribuir 8888 para cada valor que for menor que 20
dadosseq[dadosseq<20]=8888
dadosseq

array([8888, 8888, 8888, 2000,   20,   20, 8888, 8888, 8888, 8888])

In [ ]:
#transposição

dados7=np.arange(15).reshape((3,5))

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#.T inverte a matriz
dados7.T

In [ ]:
#multiplicação de matrizes com Dots

np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])